kind: Service
apiVersion: v1
metadata:
  name: jenkinstestprod
spec:
  type: NodePort
  selector:
    app: jenkinstestprod
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 30000

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkinstestprod
  labels:
    app: jenkinstestprod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkinstestprod
  template:
    metadata:
      labels:
        app: jenkinstestprod
    spec:
      containers:
      - name: jenkinstestprod
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
