kind: Service
apiVersion: v1
metadata:
  name: jenkinstestprod
spec:
  type: NodePort
  selector:
    app: jenkinstestprod
    track: canary
  ports:
  - protocol: TCP
    port: 8001
    nodePort: 8002

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkinstestprod
  labels:
    app: jenkinstestprod
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      app: jenkinstestprod
      track: canary
  template:
    metadata:
      labels:
        app: jenkinstestprod
        track: canary
    spec:
      containers:
      - name: jenkinstestprod
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8001
