kind: Service
apiVersion: v1
metadata:
  name: jenkinstestprod
spec:
  type: NodePort
  selector:
    app: jenkinstestprod
  ports:
  - protocol: TCP
    port: 8001
    nodePort: 8001

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkinstestprod
  labels:
    app: jenkinstestprod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkinstestprod
  template:
    metadata:
      labels:
        app: jenkinstestprod
    spec:
      containers:
      - name: jenkinstestprod
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8001
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: jenkinstestprod
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jenkinstestprod
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
